### ISSUE TITLE
Unable to run uam-test-scenario

### ISSUE THREAD

**Issue by vmeatsbread** [BauhausLuftfahrt/MATSim-UAM#95]
Hello! I'm new to simulating with MATSim and was interested in this UAM plugin. After installing the plugin by updating the pom.xml and rebuilding the MATSim Package, I'm unable to run the `uam-test-scenario` example. Getting an error around `swissRailRaptor`. 

`2024-09-11T10:01:27,545 ERROR MatsimRuntimeModifications:76 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Unmaterialized config group: swissRailRaptor
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:32) ~[matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.config.Config.checkConsistency(Config.java:188) ~[matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:86) ~[matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82) ~[matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) [matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) [matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92) [matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) [matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.Controler.run(Controler.java:259) [matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:65) [matsim-example-project-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
`

Any guidance would be greatly appreciated as I learn how to best use MATSim. Thank you!

**Comment by balacmi** [comment]
Dear @vmeatsbread ,

You need to check the `RunUAMScenario` class to see how to run UAM. You need to use this code or copy it to your main method. You can not just simply use the `RunMatsim` class for matsim-example-project.

https://github.com/BauhausLuftfahrt/MATSim-UAM/blob/1a4188824a3ecbdee2452ccb856f13826d8c283b/src/main/java/net/bhl/matsim/uam/run/RunUAMScenario.java#L26

**Comment by vmeatsbread** [comment]
Hi @balacm

Firstly, thank you for your help. This was a great pointer for me to head to the right direction. Before I close this issue I wanted to leave a few of my discoveries in case someone else also is in my spot.

Firstly, this thesis that I tracked down online was immensely useful: https://mediatum.ub.tum.de/doc/1596358/1596358.pdf
Second: I had to revert to Java 11 to have this run.

Thanks again for your help.

**Comment by balacmi** [comment]
Thank you, @vmeatsbread . This reminds me that I should probably make a new release of the repo, so that we can have it compatible with newest MATSim release.

**Comment by vmeatsbread** [comment]
Hi @balacmi @RRothfeld, I have been doing more research into this and came across the following paper: https://www.mdpi.com/2071-1050/13/4/2217#B38-sustainability-13-02217

I was wondering if the data used to run the San Francisco UAM example is available to be explored. I was able to track down the eqasim repo containing SF data but I don't believe this contains UAM data.

Thanks!

**Comment by RRothfeld** [comment]
Hey @vmeatsbread , sure I'm happy to share the input files used for the calculations. You can download the package here: https://1drv.ms/u/s!AuiRYsHD5pY3kfwFi9ZglKAm_TfO-A?e=KOGzQv (link valid until 31. March 2025).

**Comment by vmeatsbread** [comment]
This is incredible. Thank you so much for sharing this!

**Comment by vmeatsbread** [comment]
Thanks again for all your help @RRothfeld! Had a few more questions for you as I dug deeper. I noticed you ran with 120gb of ram - do you think it is viable to run this locally (downscaled perhaps)? I also had noticed some calls to AWS, was there some other data that I may need? The reason I ask is I get "UmlaufId could not be found. veh=veh_4976_bus" - just wanting to make sure I'm not missing anything here. 

Truly appreciate your guidance and help!

**Comment by RRothfeld** [comment]
Yes, the script where executed on AWS servers, but should run locally just as well, given similar hardware. So you should be able to run locally, but it might be substantially slower. The package contains all data that I used for the calculations for San Francisco - I just checked again. The Umlauf-ID message you get must be related to the transit schedule, but it could be a warning that does not prevent the travel time calculations from running.

But maybe that's an important info - with the package you could run travel time calculations (see runscript and its calls to e.g. net.bhl.matsim.uam.analysis.traveltimes.RunCalculateUAMTravelTimes), not a full simulation. Hope this help!

**Comment by vmeatsbread** [comment]
That was indeed the important info, thank you so much for all your help. It is greatly appreciated!
